services:
    oc_platform.antispam:
      class: OC\PlatformBundle\Antispam\OCAntispam
#    oc_platform.example:
#        class: OC\PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
