<?php

namespace OC\PlatformBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends EntityRepository
{
  public function myFindAll()
  {
    return $this
    ->createQueryBuilder('a')
    ->getQuery()
    ->getResult();
  }

  public function getAdvertWithApplications()
  {
    $qb = $this
      ->createQueryBuilder('a')
      ->leftJoin('a.applications', 'app')
      ->addSelect('app')
    ;

    return $qb
      ->getQuery()
      ->getResult()
    ;
  }
}
